(defvar filename "theString.txt")

(defun state0(strlist)
	(if (= (length strlist) 0)
		(return-from state0 0))
	(let ((sublist strlist) (n 0))
		(dolist (C strlist)
			(cond
				((STRING-EQUAL C "x") (setf n (+ n 1)))
				((STRING-EQUAL C "y") (return-from state0 (state1 (subseq sublist (+ n 1) (length sublist)))))
)))
	(return-from state0 0))

(defun state1(strlist)
	(if (= (length strlist) 0)
		(return-from state1 1))
	(let ((sublist strlist) (n 0))
		(dolist (C strlist)
			(cond
				((STRING-EQUAL C "x") (return-from state1 (state2 (subseq sublist (+ n 1) (length sublist)))))
)))
	(return-from state1 0))

(defun state2(strlist)
	(if (= (length strlist) 0)
		(return-from state2 0))
	(let ((sublist strlist) (n 0))
		(dolist (C strlist)
			(cond
				((STRING-EQUAL C "x") (setf n (+ n 1)))
				((STRING-EQUAL C "y") (return-from state2 (state3 (subseq sublist (+ n 1) (length sublist)))))
)))
	(return-from state2 0))

(defun state3(strlist)
	(if (= (length strlist) 0)
		(return-from state3 1))
	(let ((sublist strlist) (n 0))
		(dolist (C strlist)
			(cond
				((STRING-EQUAL C "x") (setf n (+ n 1)))
				((STRING-EQUAL C "z") (return-from state3 (state4 (subseq sublist (+ n 1) (length sublist)))))
)))
	(return-from state3 0))

(defun state4(strlist)
	(if (= (length strlist) 0)
		(return-from state4 0))
	(let ((sublist strlist) (n 0))
		(dolist (C strlist)
			(cond
				((STRING-EQUAL C "x") (setf n (+ n 1)))
				((STRING-EQUAL C "a") (return-from state4 (state1 (subseq sublist (+ n 1) (length sublist)))))
)))
	(return-from state4 0))

(defun checkalphabet(str alphabet)
	(dolist (c str)
		(if (find c alphabet)
			(return-from checkalphabet 1)
			(return-from checkalphabet 0))))

(defun demo ()
	(setq file (open filename :direction :input))
	(setq strlist (read file "done"))
	(princ "processing ")
	(terpri)
	(setq current-state 0)
	(setq accept 0)
	(setq alphabet '(x y z a))
	(setq inalphabet (checkalphabet strlist alphabet))
	(setq success (state0 strlist))
	(if (and (= success 1) (= inalphabet 1))
		(write "string is legal")
		(write "string is illegal")))
